spring:
  application:
    name: cloud-provider-payment #设置注册到zookeeper注册中心使用的名字
  cloud:
    zookeeper:
      connect-string: 192.168.231.134:2181 #运行在linux上的zookeeper服务端地址

#配置端口号
server:
  port: 8004

